services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: car_price_backend
    ports:
      - "8000:8000"
    environment:
      - API_ENV=production
      - PORT=8000
      - ALLOWED_ORIGINS=*
    volumes:
      - ./backend/artifacts:/app/artifacts
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: car_price_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/predict
    depends_on:
      - backend
    restart: always
